PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX lapd: <http://www.semanticweb.org/aaditya9/ontologies/2023/10/LAPD_Crime#>

SELECT ?offenceType (COUNT(?offenceType) AS ?offenceCount)
WHERE {
  ?hc rdf:type lapd:HateCrime .
  ?st rdf:type lapd:US_States .
  ?ct rdf:type lapd:US_City .
  ?lt rdf:type lapd:TypeOfLocation .
  ?bm rdf:type lapd:BiasMotivation .
  ?ot rdf:type lapd:TypeOfOffence .
  ?cr rdf:type lapd:CriminalRace .
  
  ?hc lapd:hasHateCrimeState ?st .
  ?hc lapd:hasHateCrimeCity ?ct .
  ?hc lapd:hasHateCrimeLocationType ?lt .
  ?hc lapd:hasHateCrimeBiasMotivation ?bm .
  ?hc lapd:hasHateCrimeOffence ?ot .
  ?hc lapd:hasHateCrimeCriminalRace ?cr .

  BIND(xsd:string(strafter(str(?st), "#")) AS ?state)
  BIND(xsd:string(strafter(str(?ct), "#")) AS ?city)
  BIND(xsd:integer(strafter(str(?lt), "#")) AS ?locationType)
  BIND(xsd:string(strafter(str(?bm), "#")) AS ?biasMotivation)
  BIND(xsd:string(strafter(str(?ot), "#")) AS ?offenceType)
  BIND(xsd:string(strafter(str(?cr), "#")) AS ?criminalRace)
  
  FILTER(?criminalRace = "BlackOrAfricanAmerican" && ?locationType = 0 && ?biasMotivation = "Anti-BlackOrAfricanAmerican")
}
GROUP BY ?offenceType
ORDER BY DESC(?offenceCount)
